-- V1__schema.sql  (PostgreSQL 16)
-- Legacy source: bofa-portal src/main/resources/sql/schema.sql (HSQLDB 1.8 / DB2 OLBP01)

CREATE TABLE olb_customer (
    customer_id        INTEGER      NOT NULL,
    user_id            VARCHAR(32)  NOT NULL,
    password_hash      VARCHAR(72)  NOT NULL,                 -- bcrypt "$2a$12$..." (60 chars); was CHAR(32) MD5
    first_name         VARCHAR(40)  NOT NULL,
    last_name          VARCHAR(40)  NOT NULL,
    rel_tier_cd        CHAR(2)      NOT NULL DEFAULT '00',
    last_login_ts      TIMESTAMPTZ,
    fail_cnt           SMALLINT     NOT NULL DEFAULT 0,
    stat_cd            CHAR(1)      NOT NULL DEFAULT 'A',
    CONSTRAINT pk_olb_customer           PRIMARY KEY (customer_id),
    CONSTRAINT ck_olb_customer_tier      CHECK (rel_tier_cd IN ('00','10','20','30')),
    CONSTRAINT ck_olb_customer_stat      CHECK (stat_cd IN ('A','L')),
    CONSTRAINT ck_olb_customer_fail_cnt  CHECK (fail_cnt >= 0)
);
-- legacy lookup is UPPER(OLB_USER_ID) = UPPER(?)  (CustomerDAO.java:13-15)
CREATE UNIQUE INDEX ux_olb_customer_user_id_ci ON olb_customer (UPPER(user_id));

CREATE TABLE olb_account (
    account_id         VARCHAR(12)  NOT NULL,
    customer_id        INTEGER      NOT NULL,
    acct_typ_cd        CHAR(3)      NOT NULL,
    product_name       VARCHAR(60)  NOT NULL,
    acct_nbr_last4     CHAR(4)      NOT NULL,
    cur_bal_cents      BIGINT       NOT NULL DEFAULT 0,
    avl_bal_cents      BIGINT       NOT NULL DEFAULT 0,
    ext_bank_name      VARCHAR(60),
    seq_no             SMALLINT     NOT NULL DEFAULT 0,
    stat_cd            CHAR(1)      NOT NULL DEFAULT 'A',
    CONSTRAINT pk_olb_account            PRIMARY KEY (account_id),
    CONSTRAINT fk_olb_account_customer   FOREIGN KEY (customer_id) REFERENCES olb_customer (customer_id),
    CONSTRAINT ck_olb_account_type       CHECK (acct_typ_cd IN ('DDA','SAV','EXT')),
    CONSTRAINT ck_olb_account_stat       CHECK (stat_cd IN ('A','C')),       -- 'C' closed: legacy treats any non-'A' as closed (AccountDAO.java:22,37)
    CONSTRAINT ck_olb_account_last4      CHECK (acct_nbr_last4 ~ '^[0-9]{4}$'),
    CONSTRAINT ck_olb_account_ext_bank   CHECK ((acct_typ_cd = 'EXT') = (ext_bank_name IS NOT NULL))
);
CREATE INDEX ix_olb_account_customer_seq ON olb_account (customer_id, seq_no);

CREATE TABLE olb_fee_schedule (
    xfr_typ_cd         CHAR(3)      NOT NULL,
    rel_tier_cd        CHAR(2)      NOT NULL,
    fee_cents          BIGINT       NOT NULL,
    daily_lim_cents    BIGINT       NOT NULL,
    per_txn_lim_cents  BIGINT       NOT NULL,
    eff_dt             DATE         NOT NULL,
    CONSTRAINT pk_olb_fee_schedule       PRIMARY KEY (xfr_typ_cd, rel_tier_cd),   -- same grain as legacy: one row per cell, no rate history
    CONSTRAINT ck_olb_fee_schedule_type  CHECK (xfr_typ_cd IN ('INT','EXS','EXN')),
    CONSTRAINT ck_olb_fee_schedule_tier  CHECK (rel_tier_cd IN ('00','10','20','30')),
    CONSTRAINT ck_olb_fee_schedule_nonneg CHECK (fee_cents >= 0 AND daily_lim_cents >= 0 AND per_txn_lim_cents >= 0)
);

CREATE TABLE olb_bank_holiday (
    holiday_dt         DATE         NOT NULL,
    holiday_name       VARCHAR(40)  NOT NULL,
    CONSTRAINT pk_olb_bank_holiday       PRIMARY KEY (holiday_dt)
);

CREATE TABLE olb_confirmation_seq (
    seq_dt             DATE         NOT NULL,
    last_seq           INTEGER      NOT NULL,
    CONSTRAINT pk_olb_confirmation_seq   PRIMARY KEY (seq_dt),
    CONSTRAINT ck_olb_confirmation_seq_range CHECK (last_seq BETWEEN 0 AND 999999)   -- 6-digit suffix (TransferService.java:241-242)
);

CREATE TABLE olb_transfer (
    transfer_id        BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    conf_nbr           CHAR(16)     NOT NULL,
    customer_id        INTEGER      NOT NULL,
    from_account_id    VARCHAR(12)  NOT NULL,
    to_account_id      VARCHAR(12)  NOT NULL,
    amt_cents          BIGINT       NOT NULL,
    fee_cents          BIGINT       NOT NULL DEFAULT 0,
    xfr_typ_cd         CHAR(3)      NOT NULL,
    rel_tier_cd        CHAR(2)      NOT NULL,
    freq_cd            CHAR(1)      NOT NULL DEFAULT 'O',
    sched_dt           DATE         NOT NULL,
    post_dt            DATE         NOT NULL,
    stat_cd            CHAR(1)      NOT NULL,
    memo               VARCHAR(60),
    crt_ts             TIMESTAMPTZ  NOT NULL DEFAULT now(),
    crt_chnl_cd        CHAR(3)      NOT NULL DEFAULT 'OLB',
    CONSTRAINT pk_olb_transfer           PRIMARY KEY (transfer_id),
    CONSTRAINT ux_olb_transfer_conf_nbr  UNIQUE (conf_nbr),                      -- legacy had NO uniqueness; added deliberately
    CONSTRAINT fk_olb_transfer_customer  FOREIGN KEY (customer_id)     REFERENCES olb_customer (customer_id),
    CONSTRAINT fk_olb_transfer_from      FOREIGN KEY (from_account_id) REFERENCES olb_account (account_id),
    CONSTRAINT fk_olb_transfer_to        FOREIGN KEY (to_account_id)   REFERENCES olb_account (account_id),
    CONSTRAINT ck_olb_transfer_amt       CHECK (amt_cents > 0),                  -- R1 (TransferService.java:138-143)
    CONSTRAINT ck_olb_transfer_fee       CHECK (fee_cents >= 0),
    CONSTRAINT ck_olb_transfer_accts     CHECK (from_account_id <> to_account_id),-- R2 (TransferService.java:147)
    CONSTRAINT ck_olb_transfer_type      CHECK (xfr_typ_cd IN ('INT','EXS','EXN')),
    CONSTRAINT ck_olb_transfer_tier      CHECK (rel_tier_cd IN ('00','10','20','30')),
    CONSTRAINT ck_olb_transfer_freq      CHECK (freq_cd IN ('O','W','M')),
    CONSTRAINT ck_olb_transfer_stat      CHECK (stat_cd IN ('P','S','R')),
    CONSTRAINT ck_olb_transfer_conf_fmt  CHECK (conf_nbr ~ '^XFR[0-9]{6}-[0-9]{6}$'),
    CONSTRAINT ck_olb_transfer_post_dt   CHECK (post_dt >= sched_dt)
);
-- history: WHERE customer_id=? ORDER BY crt_ts DESC, transfer_id DESC LIMIT 10   (TransferDAO.java:74-78)
CREATE INDEX ix_olb_transfer_customer_crt ON olb_transfer (customer_id, crt_ts DESC, transfer_id DESC);
-- daily external limit sum: WHERE customer_id=? AND sched_dt=? AND xfr_typ_cd IN ('EXS','EXN') AND stat_cd<>'R'   (TransferDAO.java:89-103)
CREATE INDEX ix_olb_transfer_customer_sched ON olb_transfer (customer_id, sched_dt) INCLUDE (xfr_typ_cd, stat_cd, amt_cents);
-- Reg D count: WHERE from_account_id=? AND sched_dt BETWEEN ? AND ? AND stat_cd<>'R'   (TransferDAO.java:105-119)
CREATE INDEX ix_olb_transfer_from_sched ON olb_transfer (from_account_id, sched_dt) WHERE stat_cd <> 'R';

-- Convenience views for humans / BI (domain code never uses them)
CREATE VIEW v_olb_account_dollars AS
  SELECT account_id, customer_id, acct_typ_cd, product_name, acct_nbr_last4,
         cur_bal_cents / 100.0 AS current_balance, avl_bal_cents / 100.0 AS available_balance, ext_bank_name, seq_no, stat_cd
  FROM olb_account;
CREATE VIEW v_olb_transfer_dollars AS
  SELECT transfer_id, conf_nbr, customer_id, from_account_id, to_account_id,
         amt_cents / 100.0 AS amount, fee_cents / 100.0 AS fee, (amt_cents + fee_cents) / 100.0 AS total_debit,
         xfr_typ_cd, rel_tier_cd, freq_cd, sched_dt, post_dt, stat_cd, memo, crt_ts, crt_chnl_cd
  FROM olb_transfer;
